###
GET http://localhost:8080/api/users

###

PATCH http://localhost:8080/api/users/63e7880245f039da3eebc821
Content-Type: application/json

{
   "name":"本田 宗一郎"
}

###
DELETE http://localhost:8080/api/users/63
###

POST http://localhost:8080/api/users
Content-Type: application/json

{
   "name":"ローランド",
   "bathingDay":"水　日",
   "ent":"2023/05/14",
   "remarks":"機械浴 浴前血圧測定 午前中最後に入浴"
}